### ISSUE TITLE
Dataset for reproduce

### ISSUE THREAD

**Issue by jieWANGforwork** [allenai/promptable-behaviors#1]
Hello, can I ask for procthor-10ka and object-nav-eval to reimplement the experiments?
Thanks.

**Comment by jieWANGforwork** [comment]
> Hello, can I ask for procthor-10ka and object-nav-eval to reimplement the experiments? Thanks.

**Comment by womeizhaol** [comment]
请问如何下载并在这个数据集上测评呢
